#!/bin/sh

batorcat() {
    file="$1"
    shift
    if command -v bat >/dev/null 2>&1; then
        if [ -n "${BAT_THEME:-}" ]; then
            bat --color=always --theme="$BAT_THEME" --style=numbers --pager=never "$file" "$@"
        else
            bat --color=always --style=numbers --pager=never "$file" "$@"
        fi
    else
        cat "$file"
    fi
}

image() {
    if [ -n "$WT_SESSION" ] || [ -n "$TMUX" ]; then
      # windows terminal (no sixels yet) or tmux (not much success with passthrough to iterm here)
      chafa -f symbols -s "$2x$3" --animate off --polite on "$1"
    else
      chafa -f sixels -s "$2x$3" --animate off --polite on "$1"
    fi
}

hash_file() {
    if command -v sha256sum >/dev/null 2>&1; then
        sha256sum "$1" | awk '{print $1}'
    elif command -v shasum >/dev/null 2>&1; then
        shasum -a 256 "$1" | awk '{print $1}'
    else
        cksum "$1" | awk '{print $1}'
    fi
}

cache_dir="${XDG_CACHE_HOME:-$HOME/.cache}/lf"
mkdir -p "$cache_dir" || exit 1
cache="$cache_dir/thumbnail.$(hash_file "$1")"

case "$(file -Lb --mime-type -- "$1")" in
  image/*)
    image "$1" "$2" "$3"
    ;;
  application/pdf)
    [ ! -f "${cache}.jpg" ] && pdftoppm -jpeg -f 1 -singlefile "$1" "$cache"
    image "${cache}.jpg" "$2" "$3"
    ;;
  text/*|application/json)
    batorcat "$1"
    ;;
  *)
    # lesspipe can list many archives, and even do docx files
    # if it does not work (e.g. message/rfc822) then batorcat can try
    if command -v lesspipe.sh >/dev/null 2>&1; then
      lesspipe.sh "$1" || batorcat "$1"
    elif command -v lesspipe >/dev/null 2>&1; then
      lesspipe "$1" || batorcat "$1"
    else
      batorcat "$1"
    fi
    ;;
esac
