color=131c2b
bs-hl-color=ff7a5f
caps-lock-bs-hl-color=ff7a5f
caps-lock-key-hl-color=41bf4f
inside-color=131c2b00
inside-clear-color=20493f00
inside-caps-lock-color=403f2200
inside-ver-color=183c6500
inside-wrong-color=55132700
key-hl-color=41bf4f
layout-bg-color=131c2b00
layout-border-color=595a6300
layout-text-color=eaedef
line-color=595a6300
line-clear-color=2fd0db00
line-caps-lock-color=f0c06000
line-ver-color=57b0ff00
line-wrong-color=ff7a5f00
ring-color=57b0ff
ring-clear-color=2fd0db
ring-caps-lock-color=f0c060
ring-ver-color=57b0ff
ring-wrong-color=ff7a5f
separator-color=595a6300
text-color=eaedef
text-clear-color=2fd0db
text-caps-lock-color=f0c060
text-ver-color=57b0ff
text-wrong-color=ff7a5f
