color=0d0e1c
bs-hl-color=ff6b55
caps-lock-bs-hl-color=ff6b55
caps-lock-key-hl-color=44bc44
inside-color=0d0e1c00
inside-clear-color=092f1f00
inside-caps-lock-color=381d0f00
inside-ver-color=1640b000
inside-wrong-color=3a0c1400
key-hl-color=44bc44
layout-bg-color=0d0e1c00
layout-border-color=61647a00
layout-text-color=ffffff
line-color=61647a00
line-clear-color=00d3d000
line-caps-lock-color=fec43f00
line-ver-color=2fafff00
line-wrong-color=ff5f5900
ring-color=c6daff
ring-clear-color=00d3d0
ring-caps-lock-color=fec43f
ring-ver-color=2fafff
ring-wrong-color=ff5f59
separator-color=61647a00
text-color=ffffff
text-clear-color=00d3d0
text-caps-lock-color=fec43f
text-ver-color=79a8ff
text-wrong-color=ff6b55
