color=002b36
bs-hl-color=cb4b16
caps-lock-bs-hl-color=cb4b16
caps-lock-key-hl-color=859900
inside-color=002b3600
inside-clear-color=07364200
inside-caps-lock-color=3b341c00
inside-ver-color=07364200
inside-wrong-color=42242a00
key-hl-color=859900
layout-bg-color=002b3600
layout-border-color=586e7500
layout-text-color=93a1a1
line-color=586e7500
line-clear-color=2aa19800
line-caps-lock-color=b5890000
line-ver-color=268bd200
line-wrong-color=dc322f00
ring-color=268bd2
ring-clear-color=2aa198
ring-caps-lock-color=b58900
ring-ver-color=268bd2
ring-wrong-color=dc322f
separator-color=586e7500
text-color=93a1a1
text-clear-color=2aa198
text-caps-lock-color=b58900
text-ver-color=3495df
text-wrong-color=f45a55
