;;; init-elfeed.el -*- lexical-binding: t -*-

;; Elfeed
(use-package elfeed
  :ensure t
  :custom
  ;(elfeed-db-directory
  ; (expand-file-name "elfeed" user-emacs-directory))
  (elfeed-show-entry-switch 'display-buffer)
  :bind ("C-x w" . elfeed)
  :config
  (setq elfeed-feeds
        '(("http://asert.arbornetworks.com/feed/" security)
          ("http://feeds.trendmicro.com/Anti-MalwareBlog/" security)
          ("http://researchcenter.paloaltonetworks.com/unit42/feed/" security)
          ("https://www.proofpoint.com/rss.xml" security)
          ("https://www.bellingcat.com/feed/" security)
          ("http://www.reddit.com/r/ReverseEngineering/.rss" security  reddit)
          ("https://fossacademic.tech/feed.xml" academic blog tech)
          ("https://nomasters.io/index.xml" blog tech)
          ("https://www.reddit.com/r/listentothis/.rss" music reddit)
          ("https://www.youtube.com/feeds/videos.xml?channel_id=UC--DwaiMV-jtO-6EvmKOnqg" youtube) ;; OA Labs
          ("https://www.youtube.com/feeds/videos.xml?channel_id=UCbpMy0Fg74eXXkvxJrtEn3w" youtube) ;; Bon Apetit
          ("https://www.youtube.com/feeds/videos.xml?channel_id=UC5fdssPqmmGhkhsJi4VcckA" youtube) ;; Innuendo Studios
          ("https://usesthis.com/feed.atom" tech)
          ("https://www.kcrw.com/culture/shows/nocturne/rss.xml" podcast) ;; Nocturne
          ("https://www.youtube.com/feeds/videos.xml?channel_id=UCGzvjCcqc9U6KkmgNx9t6VA" youtube)
          ("https://www.youtube.com/feeds/videos.xml?channel_id=UCTfabOKD7Yty6sDF4POBVqA" youtube)
          ("https://www.youtube.com/feeds/videos.xml?channel_id=UC2eYFnH61tmytImy1mTYvhA" youtube)
          ("https://www.youtube.com/feeds/videos.xml?channel_id=UCxQKHvKbmSzGMvUrVtJYnUA" youtube)
          ("https://www.youtube.com/feeds/videos.xml?channel_id=UC3jSNmKWYA04R47fDcc1ImA" youtube)
          ("https://www.youtube.com/feeds/videos.xml?channel_id=UCsnGwSIHyoYN0kiINAGUKxg" youtube)
          ("https://www.youtube.com/feeds/videos.xml?channel_id=UCFFLP0dKesrKWccYscdAr9A" youtube)
          ("https://www.youtube.com/feeds/videos.xml?channel_id=UC0A3ldncnGQ1M_RU2Wb4L2A" youtube)
          ("https://www.youtube.com/feeds/videos.xml?channel_id=UC0uTPqBCFIpZxlz_Lv1tk_g" youtube)
          ("https://www.youtube.com/feeds/videos.xml?channel_id=UCYO_jab_esuFRV4b17AJtAw" youtube)
          ("https://www.youtube.com/feeds/videos.xml?channel_id=UCxwcmRAmBRzZMNS37dCgmHA" youtube)
          ("https://www.youtube.com/feeds/videos.xml?channel_id=UCLx053rWZxCiYWsBETgdKrQ" youtube)
          ("https://www.youtube.com/feeds/videos.xml?channel_id=UCHugE6eRhqB9_AZQh4DDbIw" youtube)
          ("https://www.youtube.com/feeds/videos.xml?channel_id=UCEBb1b_L6zDS3xTUrIALZOw" youtube)
          ("https://www.youtube.com/feeds/videos.xml?channel_id=UC8uT9cgJorJPWu7ITLGo9Ww" youtube)
          ("https://www.youtube.com/feeds/videos.xml?channel_id=UCts-8ZqS339n-9nxy3DN8Cg" youtube)
          ("https://www.youtube.com/feeds/videos.xml?channel_id=UCVls1GmFKf6WlTraIb_IaJg" youtube)
          ("https://www.youtube.com/feeds/videos.xml?channel_id=UCuHJawjMUOk4gjywwDg727w" youtube)
          ("https://www.tecmint.com/feed/" tech)
          ("https://www.archlinux.org/feeds/news/" tech)
          ("https://karl-voit.at/feeds/lazyblorg-all.atom_1.0.links-and-content.xml" blog tech)
          ("http://leancrew.com/all-this/feed/" blog tech)
          ("http://stadt-bremerhaven.de/feed/" blog tech)
          ("http://feeds.feedburner.com/Makeuseof" tech)
          ("https://lukesmith.xyz/index.xml" blog tech)
          ("https://100r.co/links/rss.xml" blog tech)
          ("https://webzine.puffy.cafe/atom.xml" tech)
          ("https://jmmv.dev/feed.xml" blog tech)
          ("https://jcs.org/rss" blog tech)
          ("https://dataswamp.org/~solene/rss.xml" blog tech)
          ("https://bsdly.blogspot.com/feeds/posts/default" blog bsd tech)
          ("https://xeiaso.net/blog.rss" blog tech)
          ("https://www.tumfatig.net/index.xml" blog bsd tech)
          ("https://www.kuketz-blog.de/category/artikel/feed/" blog security)
          ("https://thevaluable.dev/index.xml" blog tech)
          ("https://andreafortuna.org/feed.xml" blog tech)
          ("https://codemadness.org/atom_content.xml" blog tech)
          ("https://begriffs.com/atom.xml" blog tech)
          ("https://sive.rs/en.atom" blog literature misc tech)
          ("https://news.nononsenseapps.com/index.atom" blog tech)
          ("https://www.geeklan.co.uk/?feed=rss2" blog tech)
          ("https://herrbischoff.com/index.xml" blog tech)
          ("https://it-notes.dragas.net/index.xml" blog tech)
          ("https://michael.stapelberg.ch/feed.xml" blog tech)
          ("https://ratfactor.com/atom.xml" blog tech)
          ("https://rubenerd.com/feed/" blog tech)
          ("https://adol.pw/index.xml" blog tech)
          ("https://electro.pizza/feed.xml" blog tech)
          ("https://jcs.org/rss" blog tech)
          ("https://kzimmermann.0x.no/articles/atom.xml" blog tech)
          ("https://blog.meain.io/feed.xml" blog tech)
          ("https://unixsheikh.com/feed.rss" blog tech)
          ("https://vermaden.wordpress.com/feed/" blog tech)
          ("https://crys.site/blog/index.xml" blog bsd tech)
          ("https://www.boucek.me/index.xml" blog tech)
          ("https://karthinks.com/software/index.xml" blog emacs tech)
          ("https://batsov.com/atom.xml" blog emacs tech)
          ("https://michaelneuper.com/index.xml" blog emacs tech)))
  :commands (elfeed))

(provide 'init-elfeed)
