# Catppuccin Macchiato

foreground              #cad3f5
background              #24273a
selection_foreground    #cad3f5
selection_background    #454a5f
cursor                  #f4dbd6
cursor_text_color       #181926
url_color               #8aadf4

active_border_color     #8aadf4
inactive_border_color   #5b6078
bell_border_color       #ed8796

active_tab_foreground   #cad3f5
active_tab_background   #5b6078
inactive_tab_foreground #a5adcb
inactive_tab_background #363a4f
tab_bar_background      #181926

color0  #494d64
color1  #ed8796
color2  #a6da95
color3  #eed49f
color4  #8aadf4
color5  #f5bde6
color6  #8bd5ca
color7  #b8c0e0
color8  #5b6078
color9  #ed8796
color10 #a6da95
color11 #eed49f
color12 #8aadf4
color13 #f5bde6
color14 #8bd5ca
color15 #a5adcb
