foreground              #1F1F1F
background              #F5F5F5
selection_foreground    #F5F5F5
selection_background    #DE5735

url_color               #036A96

# black
color0                  #F5F5F5
color8                  #635D97

# red
color1                  #CB3A2A
color9                  #D74C3D

#green
color2                  #14710A
color10                 #198D0C

# yellow
color3                  #846E15
color11                 #9E841A

# blue
color4                  #644AC9
color12                 #7862D0

# magenta
color5                  #A3144D
color13                 #BF185A

# cyan
color6                  #036A96
color14                 #047FB4

# white
color7                  #1F1F1F
color15                 #2C2B31

# cursor colors
cursor                  #DE5735
cursor_text_color       background

# tab bar colors
active_tab_foreground   #F5F5F5
active_tab_background   #1F1F1F
inactive_tab_foreground #F5F5F5
inactive_tab_background #635D97

# marks
mark1_foreground #F5F5F5
mark1_background #CB3A2A
