# Ef Maris Light palette by Protesilaos Stavrou, adapted for Kitty.

foreground              #151a27
background              #edf4f8
selection_foreground    #151a27
selection_background    #c8dcff
cursor                  #036f99
cursor_text_color       #edf4f8
url_color               #375cc6

active_border_color     #375cc6
inactive_border_color   #a2a6af
bell_border_color       #d00000

active_tab_foreground   #151a27
active_tab_background   #a0c2ef
inactive_tab_foreground #676470
inactive_tab_background #dbe4e6
tab_bar_background      #e0e7ef

color0  #151a27
color1  #c3303a
color2  #007010
color3  #805a1f
color4  #375cc6
color5  #80308f
color6  #1f66af
color7  #a2a6af
color8  #676470
color9  #d00000
color10 #007047
color11 #8b4400
color12 #003faf
color13 #5f2fba
color14 #006f70
color15 #151a27
