# Ef Maris Dark palette by Protesilaos Stavrou, adapted for Kitty.

foreground              #eaedef
background              #131c2b
selection_foreground    #eaedef
selection_background    #183c65
cursor                  #8fdfff
cursor_text_color       #131c2b
url_color               #57b0ff

active_border_color     #57b0ff
inactive_border_color   #595a63
bell_border_color       #ff7a5f

active_tab_foreground   #ecf0ff
active_tab_background   #2f527b
inactive_tab_foreground #969faf
inactive_tab_background #2a3341
tab_bar_background      #1d2c39

color0  #131c2b
color1  #ff6f6f
color2  #41bf4f
color3  #d0d24f
color4  #57b0ff
color5  #f59acf
color6  #2fd0db
color7  #969faf
color8  #4a5664
color9  #ff7a5f
color10 #30c489
color11 #f0c060
color12 #12b4ff
color13 #cf90ff
color14 #65d5a8
color15 #eaedef
