# Modus Operandi Tinted palette by Protesilaos Stavrou, adapted for Kitty.

foreground              #000000
background              #fbf7f0
selection_foreground    #000000
selection_background    #bfc9ff
cursor                  #000000
cursor_text_color       #fbf7f0
url_color               #0031a9

active_border_color     #193668
inactive_border_color   #9f9690
bell_border_color       #a60000

active_tab_foreground   #000000
active_tab_background   #c9b9b0
inactive_tab_foreground #595959
inactive_tab_background #dfd5cf
tab_bar_background      #efe9dd

color0  #000000
color1  #a60000
color2  #006300
color3  #6d5000
color4  #0031a9
color5  #721045
color6  #00598b
color7  #9f9690
color8  #595959
color9  #972500
color10 #00603f
color11 #894000
color12 #3546c2
color13 #531ab6
color14 #005f5f
color15 #595959
