#!/bin/sh

while IFS= read -r file; do
	case "$1" in
	"C-d")
		rm -- "$file"
		;;
	"w")
		if [ -n "${SWAYSOCK:-}" ] && command -v swaymsg >/dev/null 2>&1; then
			swaymsg output "*" bg "$file" fill >/dev/null
		else
			feh --bg-fill "$file"
		fi
		notify-send -i "$file" "Wallpaper changed ..."
		;;
	"g")
		gimp "$file" &
		;;
	esac
done
