# Loaded automatically by Kitty when the operating system prefers dark colors.
# Choose the dark partner of the palette in light-theme.auto.conf.
include themes/ef-maris-dark.conf
# include themes/modus-vivendi-tinted.conf
# include themes/catppuccin-macchiato.conf
# include themes/solarized-dark.conf
