# Loaded automatically by Kitty when the operating system prefers light colors.
# Choose one light palette here and its matching dark palette in
# dark-theme.auto.conf.
include themes/ef-maris-light.conf
# include themes/modus-operandi-tinted.conf
# include themes/catppuccin-latte.conf
# include themes/solarized-light.conf
